language: python

python:
  - 3.5
  - 3.6

before_install:
  - pip install poetry pytest

# Install rinse
install:
  - poetry install -v

# Command to run tests
# nosetests is being used as a default
script: pytest tests
